apiVersion: v2
name: minio-storage-system
description: A Helm chart for MinIO Scalable Storage System
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - minio
  - storage
  - microservices
home: https://github.com/your-org/minio-fullstack-storage
sources:
  - https://github.com/your-org/minio-fullstack-storage
maintainers:
  - name: DevOps Team
    email: devops@yourcompany.com
dependencies:
  - name: minio
    version: 5.0.14
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
