apiVersion: v1
kind: Namespace
metadata:
  name: minio-storage
  labels:
    name: minio-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-storage-config
  namespace: minio-storage
data:
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY_ID: "minioadmin"
  MINIO_SECRET_ACCESS_KEY: "minioadmin"
  MINIO_USE_SSL: "false"
  MINIO_REGION: "us-east-1"
  REDIS_ADDR: "redis-service:6379"
  NATS_URL: "nats://nats-service:4222"
  JWT_SECRET: "your-super-secret-jwt-key-here"
  USERS_BUCKET: "users"
  POSTS_BUCKET: "posts"
  FILES_BUCKET: "files"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-secret
  namespace: minio-storage
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-storage
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: minio-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: minio-storage
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: minio-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2-alpine
        ports:
        - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: minio-storage
spec:
  type: ClusterIP
  ports:
  - port: 4222
    targetPort: 4222
  selector:
    app: nats
